# Generated by Django 3.1.5 on 2021-04-03 18:05

import core.representantetecnico.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bodega', '0002_auto_20210403_1305'),
        ('login', '0001_initial'),
        ('tecnicolaboratorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprasPublicas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('llegada_bodega', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha llegada a bodega')),
                ('hora_llegada_bodega', models.TimeField(default=django.utils.timezone.now, verbose_name='Hora llegada a bodega')),
                ('convocatoria', models.IntegerField(blank=True, null=True, validators=[core.representantetecnico.validators.validate_compras_convocatoria])),
                ('pedido_compras_publicas', models.FileField(null=True, upload_to='compras_publicas/%Y/%m/%d')),
                ('guia_transporte', models.FileField(null=True, upload_to='compras_publicas/%Y/%m/%d')),
                ('factura', models.FileField(null=True, upload_to='compras_publicas/%Y/%m/%d')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
            ],
            options={
                'verbose_name': 'Compra Publica',
                'verbose_name_plural': 'Compras Publicas',
                'db_table': 'compras_publicas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ComprasPublicasDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('cantidad', models.DecimalField(decimal_places=4, default=0, max_digits=8, null=True, verbose_name='cantidad')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='representantetecnico.compraspublicas', verbose_name='Compra')),
            ],
            options={
                'verbose_name': 'Compra Publica Detalle',
                'verbose_name_plural': 'Compras Publicas Detalles',
                'db_table': 'detalle_compra_publica',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EstadoTransaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Descripcion')),
                ('is_active', models.BooleanField(default=True, editable=False)),
            ],
            options={
                'verbose_name': 'Estado de transacción',
                'verbose_name_plural': 'Estado de transacciones',
                'db_table': 'estado_transaccion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InformesMensuales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('year', models.IntegerField(default=2021, verbose_name='Año')),
                ('is_editable', models.BooleanField(default=True, editable=False)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tecnicolaboratorio.laboratorio', verbose_name='Laboratorio')),
                ('laboratorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='laboratorista')),
            ],
            options={
                'verbose_name': 'Informe mensual',
                'verbose_name_plural': 'Informes mensuales',
                'db_table': 'informes_mensuales',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InformesMensualesDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('cantidad', models.DecimalField(decimal_places=4, default=0, max_digits=8, null=True, verbose_name='cantidad')),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='representantetecnico.informesmensuales', verbose_name='Informe')),
            ],
            options={
                'verbose_name': 'Informe mensual Detalle',
                'verbose_name_plural': 'Informes mensuales Detalles',
                'db_table': 'detalle_informe_mensual',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre del mes')),
                ('numero', models.IntegerField(verbose_name='Numero de mes')),
            ],
            options={
                'verbose_name': 'Mes',
                'verbose_name_plural': 'Meses',
                'db_table': 'mes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('nombre_actividad', models.CharField(max_length=150, null=True, verbose_name='Nombre de proyecto')),
                ('documento_solicitud', models.FileField(null=True, upload_to='solicitud/%Y/%m/%d')),
                ('codigo_solicitud', models.CharField(max_length=50, null=True, verbose_name='Codigo de solicitud')),
                ('fecha_autorizacion', models.DateTimeField(editable=False, null=True)),
                ('observacion_representante', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('observacion_bodega', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('estado_solicitud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='representantetecnico.estadotransaccion', verbose_name='Estados solicitud')),
                ('laboratorio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tecnicolaboratorio.laboratorio', verbose_name='Laboratorio')),
                ('responsable_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.persona', verbose_name='Responsable de actividad')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'db_table': 'solicitud',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion')),
                ('is_active', models.BooleanField(default=True, editable=False)),
            ],
            options={
                'verbose_name': 'Tipo de actividad',
                'verbose_name_plural': 'Tipos de actividades',
                'db_table': 'tipo_actividad',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoMovimientoInventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Tipo de movimiento de inventario',
                'verbose_name_plural': 'Tipos de movimientos de inventario',
                'db_table': 'tipo_movimiento_inventario',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre de unidad de medida')),
                ('simbolo', models.CharField(max_length=5, null=True, verbose_name='Simbolo de la unidad de medida')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Unidad de medida',
                'verbose_name_plural': 'Unidades de medida',
                'db_table': 'unidad_medida',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sustancia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de sustancia')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción de la sustancia')),
                ('cupo_autorizado', models.DecimalField(decimal_places=4, default=0, max_digits=9, verbose_name='Cupo autorizado')),
                ('unidad_medida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='representantetecnico.unidadmedida', verbose_name='Unidad de medida')),
                ('user_creation', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_representantetecnico_sustancia', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_representantetecnico_sustancia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sustancia',
                'verbose_name_plural': 'Sustancias',
                'db_table': 'sustancia',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('cantidad', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('bodega', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bodega.bodega')),
                ('laboratorio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tecnicolaboratorio.laboratorio')),
                ('sustancia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='representantetecnico.sustancia')),
                ('user_creation', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_representantetecnico_stock', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_representantetecnico_stock', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock sustancia',
                'verbose_name_plural': 'Stock sustancias',
                'db_table': 'stock',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('cantidad_solicitada', models.DecimalField(decimal_places=4, default=0, max_digits=8, null=True, verbose_name='Cantidad solicitada')),
                ('cantidad_entregada', models.DecimalField(decimal_places=4, default=0, max_digits=8, null=True, verbose_name='Cantidad entregada')),
                ('cantidad_consumida', models.DecimalField(decimal_places=4, default=0, max_digits=8, null=True, verbose_name='Cantidad consumida')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='representantetecnico.solicitud', verbose_name='Solicitud')),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='representantetecnico.stock', verbose_name='Stock')),
                ('user_creation', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_representantetecnico_solicituddetalle', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_representantetecnico_solicituddetalle', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud Detalle',
                'verbose_name_plural': 'Solicitud Detalles',
                'db_table': 'detalle_solicitud',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='solicitud',
            name='tipo_actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='representantetecnico.tipoactividad', verbose_name='Tipo de actividad'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='user_creation',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_representantetecnico_solicitud', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='user_updated',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_representantetecnico_solicitud', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Repositorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('nombre_usuario', models.CharField(max_length=500, verbose_name='Nombre archivo(usuario)')),
                ('nombre_real', models.CharField(max_length=500, verbose_name='Nombre archivo(real)')),
                ('url', models.CharField(max_length=500, verbose_name='Ruta archivo')),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_recicle_bin', models.BooleanField(default=False)),
                ('is_file', models.BooleanField(default=False)),
                ('is_dir', models.BooleanField(default=False)),
                ('user_creation', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_representantetecnico_repositorio', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_representantetecnico_repositorio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Repositorio',
                'verbose_name_plural': 'Repositorios',
                'db_table': 'repositorio',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de empresa')),
                ('ruc', models.CharField(max_length=13, unique=True, verbose_name='Ruc')),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('user_creation', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_representantetecnico_proveedor', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_representantetecnico_proveedor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'proveedor',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('cantidad_movimiento', models.DecimalField(decimal_places=4, default=0, max_digits=9, verbose_name='Cantidad movimiento')),
                ('compra_publica_detalle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='representantetecnico.compraspublicasdetalle')),
                ('informe_mensual_detalle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='representantetecnico.informesmensualesdetalle')),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='representantetecnico.stock')),
                ('tipo_movimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='representantetecnico.tipomovimientoinventario', verbose_name='Tipo de movimiento de inventario')),
                ('user_creation', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_representantetecnico_inventario', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_representantetecnico_inventario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'inventario',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='informesmensualesdetalle',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='representantetecnico.stock', verbose_name='Stock'),
        ),
        migrations.AddField(
            model_name='informesmensualesdetalle',
            name='user_creation',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_representantetecnico_informesmensualesdetalle', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='informesmensualesdetalle',
            name='user_updated',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_representantetecnico_informesmensualesdetalle', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='informesmensuales',
            name='mes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='representantetecnico.mes', verbose_name='Mes'),
        ),
        migrations.AddField(
            model_name='informesmensuales',
            name='user_creation',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_representantetecnico_informesmensuales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='informesmensuales',
            name='user_updated',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_representantetecnico_informesmensuales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DesgloseInfomeMensualDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('documento', models.FileField(null=True, upload_to='informemensual/sustancias/desglose/%Y/%m/%d')),
                ('cantidad', models.DecimalField(decimal_places=4, default=0, max_digits=8, null=True, verbose_name='cantidad')),
                ('informe_mensual_detalle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='representantetecnico.informesmensualesdetalle')),
                ('solicitud_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='representantetecnico.solicituddetalle')),
                ('user_creation', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_representantetecnico_desgloseinfomemensualdetalle', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_representantetecnico_desgloseinfomemensualdetalle', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Desglose mensual',
                'verbose_name_plural': 'Desgloses mesuales',
                'db_table': 'desglose_detalle_informe_mensual',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='compraspublicasdetalle',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='representantetecnico.stock', verbose_name='Stock'),
        ),
        migrations.AddField(
            model_name='compraspublicasdetalle',
            name='user_creation',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_representantetecnico_compraspublicasdetalle', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compraspublicasdetalle',
            name='user_updated',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_representantetecnico_compraspublicasdetalle', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compraspublicas',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='representantetecnico.proveedor', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='compraspublicas',
            name='estado_compra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='representantetecnico.estadotransaccion', verbose_name='Estado de compras'),
        ),
        migrations.AddField(
            model_name='compraspublicas',
            name='user_creation',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_representantetecnico_compraspublicas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compraspublicas',
            name='user_updated',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_representantetecnico_compraspublicas', to=settings.AUTH_USER_MODEL),
        ),
    ]
