# Generated by Django 3.1.5 on 2021-03-24 02:42

import core.representantetecnico.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bodega', '0002_auto_20210323_2142'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tecnicolaboratorio', '0001_initial'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprasPublicas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('llegada_bodega', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha llegada a bodega')),
                ('hora_llegada_bodega', models.TimeField(default=django.utils.timezone.now, verbose_name='Hora llegada a bodega')),
                ('convocatoria', models.IntegerField(blank=True, null=True, validators=[core.representantetecnico.validators.validate_compras_convocatoria])),
                ('pedido_compras_publicas', models.FileField(null=True, upload_to='compras_publicas/%Y/%m/%d')),
                ('guia_transporte', models.FileField(null=True, upload_to='compras_publicas/%Y/%m/%d')),
                ('factura', models.FileField(null=True, upload_to='compras_publicas/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Compra Publica',
                'verbose_name_plural': 'Compras Publicas',
                'db_table': 'compras_publicas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EstadoTransaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Descripcion')),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('user_creation', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_representantetecnico_estadotransaccion', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_representantetecnico_estadotransaccion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estado de transacción',
                'verbose_name_plural': 'Estado de transacciones',
                'db_table': 'estado_transaccion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('nombre_actividad', models.CharField(max_length=150, null=True, verbose_name='Nombre de proyecto')),
                ('documento_solicitud', models.FileField(blank=True, null=True, upload_to='solicitud/%Y/%m/%d')),
                ('fecha_autorizacion', models.DateTimeField(editable=False, null=True)),
                ('estado_solicitud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='representantetecnico.estadotransaccion', verbose_name='Estados solicitud')),
                ('laboratorio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tecnicolaboratorio.laboratorio', verbose_name='Laboratorio')),
                ('responsable_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.persona', verbose_name='Responsable de actividad')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'db_table': 'solicitud',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripcion')),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('user_creation', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_representantetecnico_tipodocumento', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_representantetecnico_tipodocumento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documentos',
                'db_table': 'tipo_documento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('nombre', models.CharField(max_length=20, unique=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion')),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('user_creation', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_representantetecnico_tipoactividad', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_representantetecnico_tipoactividad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de actividad',
                'verbose_name_plural': 'Tipos de actividades',
                'db_table': 'tipo_actividad',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=8, null=True, verbose_name='cantidad')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='representantetecnico.solicitud', verbose_name='Solicitud')),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bodega.stock', verbose_name='Stock')),
                ('user_creation', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_representantetecnico_solicituddetalle', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_representantetecnico_solicituddetalle', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud Detalle',
                'verbose_name_plural': 'Solicitud Detalles',
                'db_table': 'detalle_solicitud',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='solicitud',
            name='tipo_actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='representantetecnico.tipoactividad', verbose_name='Tipo de actividad'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='user_creation',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_representantetecnico_solicitud', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='user_updated',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_representantetecnico_solicitud', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Repositorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('nombre_usuario', models.CharField(max_length=500, verbose_name='Nombre archivo(usuario)')),
                ('nombre_real', models.CharField(max_length=500, verbose_name='Nombre archivo(real)')),
                ('url', models.CharField(max_length=500, verbose_name='Ruta archivo')),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_recicle_bin', models.BooleanField(default=False)),
                ('is_file', models.BooleanField(default=False)),
                ('is_dir', models.BooleanField(default=False)),
                ('user_creation', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_representantetecnico_repositorio', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_representantetecnico_repositorio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Repositorio',
                'verbose_name_plural': 'Repositorios',
                'db_table': 'repositorio',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de empresa')),
                ('ruc', models.CharField(max_length=13, unique=True, verbose_name='Ruc')),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('user_creation', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_representantetecnico_proveedor', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_representantetecnico_proveedor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'proveedor',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('url_documento', models.CharField(max_length=200, unique=True)),
                ('compra_publica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='representantetecnico.compraspublicas')),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='representantetecnico.solicitud')),
                ('tipo_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='representantetecnico.tipodocumento')),
                ('user_creation', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_representantetecnico_documento', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_representantetecnico_documento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'documento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ComprasPublicasDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=8, null=True, verbose_name='cantidad')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='representantetecnico.compraspublicas', verbose_name='Compra')),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bodega.stock', verbose_name='Stock')),
                ('user_creation', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_representantetecnico_compraspublicasdetalle', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_representantetecnico_compraspublicasdetalle', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compra Publica Detalle',
                'verbose_name_plural': 'Compras Publicas Detalles',
                'db_table': 'detalle_compra_publica',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='compraspublicas',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='representantetecnico.proveedor', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='compraspublicas',
            name='estado_compra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='representantetecnico.estadotransaccion', verbose_name='Estado de compras'),
        ),
        migrations.AddField(
            model_name='compraspublicas',
            name='user_creation',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_representantetecnico_compraspublicas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compraspublicas',
            name='user_updated',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_representantetecnico_compraspublicas', to=settings.AUTH_USER_MODEL),
        ),
    ]
