# Generated by Django 3.1.5 on 2021-03-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representantetecnico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='documento_solicitud',
            field=models.FileField(null=True, upload_to='solicitud/%Y/%m/%d'),
        ),
    ]
