# Generated by Django 3.1.5 on 2021-04-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representantetecnico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mes',
            name='nombre',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nombre del mes'),
        ),
        migrations.AlterField(
            model_name='mes',
            name='numero',
            field=models.IntegerField(unique=True, verbose_name='Numero de mes'),
        ),
    ]
