# Generated by Django 3.1.5 on 2021-02-16 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tecnicolaboratorio', '0002_auto_20210214_1826'),
        ('representantetecnico', '0002_auto_20210214_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='categoria',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='laboratorio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tecnicolaboratorio.laboratorio', verbose_name='Laboratorio'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='nombre_proyecto',
            field=models.CharField(max_length=150, null=True, verbose_name='Nombre de proyecto'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Solicitud'),
        ),
    ]
