# Generated by Django 3.1.5 on 2021-02-24 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representantetecnico', '0002_auto_20210224_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compraspublicas',
            name='factura',
            field=models.FileField(null=True, upload_to='compras_publicas/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='compraspublicas',
            name='guia_transporte',
            field=models.FileField(null=True, upload_to='compras_publicas/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='compraspublicas',
            name='pedido_compras_publicas',
            field=models.FileField(null=True, upload_to='compras_publicas/%Y/%m/%d'),
        ),
    ]
