# Generated by Django 3.1.5 on 2021-03-25 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0004_auto_20210325_1041'),
        ('tecnicolaboratorio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('representantetecnico', '0003_auto_20210324_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformesMensuales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tecnicolaboratorio.laboratorio', verbose_name='Laboratorio')),
                ('laboratorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='laboratorista')),
                ('user_creation', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_representantetecnico_informesmensuales', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_representantetecnico_informesmensuales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Informe mensual',
                'verbose_name_plural': 'Informes mensuales',
                'db_table': 'informes_mensuales',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='estadotransaccion',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='estadotransaccion',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='estadotransaccion',
            name='user_creation',
        ),
        migrations.RemoveField(
            model_name='estadotransaccion',
            name='user_updated',
        ),
        migrations.RemoveField(
            model_name='tipoactividad',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='tipoactividad',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='tipoactividad',
            name='user_creation',
        ),
        migrations.RemoveField(
            model_name='tipoactividad',
            name='user_updated',
        ),
        migrations.RemoveField(
            model_name='tipodocumento',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='tipodocumento',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='tipodocumento',
            name='user_creation',
        ),
        migrations.RemoveField(
            model_name='tipodocumento',
            name='user_updated',
        ),
        migrations.CreateModel(
            name='InformesMensualesDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=8, null=True, verbose_name='cantidad')),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='representantetecnico.informesmensuales', verbose_name='Informe')),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bodega.stock', verbose_name='Stock')),
                ('user_creation', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_representantetecnico_informesmensualesdetalle', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_representantetecnico_informesmensualesdetalle', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Informe mensual Detalle',
                'verbose_name_plural': 'Informes mensuales Detalles',
                'db_table': 'detalle_informe_mensual',
                'ordering': ['id'],
            },
        ),
    ]
