# Generated by Django 3.1.5 on 2021-04-04 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('representantetecnico', '0003_solicitud_bodega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informesmensuales',
            name='is_editable',
        ),
        migrations.AddField(
            model_name='informesmensuales',
            name='estado_informe',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='representantetecnico.estadotransaccion'),
        ),
    ]
