# Generated by Django 3.1.5 on 2021-03-04 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0013_remove_sustancia_cantidad'),
        ('representantetecnico', '0003_auto_20210224_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compraspublicasdetalle',
            name='sustancia',
        ),
        migrations.AddField(
            model_name='compraspublicasdetalle',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bodega.stock', verbose_name='Stock'),
        ),
    ]
