# Generated by Django 3.1.5 on 2021-02-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representantetecnico', '0003_auto_20210216_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='fecha_solicitud',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='documento_solicitud',
            field=models.FileField(blank=True, null=True, upload_to='solicitud/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha_autorizacion',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='is_autorized',
            field=models.BooleanField(default=False, null=True, verbose_name='Autorizada'),
        ),
    ]
