# Generated by Django 3.1.5 on 2021-03-18 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('representantetecnico', '0004_auto_20210304_0140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='nombre_proyecto',
            new_name='nombre_actividad',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='facultad',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='responsable_actividad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='representantetecnico.persona', verbose_name='Responsable de actividad'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('nombre', models.CharField(max_length=20, unique=True, verbose_name='Nombre de la categoria')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('user_creation', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_representantetecnico_tipoactividad', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_representantetecnico_tipoactividad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de actividad',
                'verbose_name_plural': 'Tipos de actividades',
                'db_table': 'tipo_actividad',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='solicitud',
            name='tipo_actividad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='representantetecnico.tipoactividad', verbose_name='Tipo de actividad'),
            preserve_default=False,
        ),
    ]
