# Generated by Django 3.1.5 on 2021-04-08 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0002_auto_20210403_1305'),
        ('representantetecnico', '0004_auto_20210403_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='compraspublicas',
            name='bodega',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bodega.bodega', verbose_name='Bodega'),
        ),
    ]
