# Generated by Django 3.1.5 on 2021-03-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representantetecnico', '0004_auto_20210325_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='observacion',
            new_name='observacion_bodega',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='observacion_representante',
            field=models.TextField(blank=True, null=True, verbose_name='Observación'),
        ),
    ]
