# Generated by Django 3.1.5 on 2021-03-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representantetecnico', '0005_auto_20210326_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicituddetalle',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='solicituddetalle',
            name='cantidad_entregada',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True, verbose_name='Cantidad entregada'),
        ),
        migrations.AddField(
            model_name='solicituddetalle',
            name='cantidad_solicitada',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True, verbose_name='Cantidad solicitada'),
        ),
    ]
