# Generated by Django 3.1.5 on 2021-03-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representantetecnico', '0005_auto_20210318_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoactividad',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='tipoactividad',
            name='nombre',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nombre'),
        ),
    ]
