# Generated by Django 3.1.5 on 2021-04-08 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('representantetecnico', '0006_inventario_solicitud_detalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicituddetalle',
            name='stock',
        ),
        migrations.AddField(
            model_name='solicituddetalle',
            name='sustancia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='representantetecnico.sustancia', verbose_name='Sustancia'),
        ),
    ]
