# Generated by Django 3.1.5 on 2021-03-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representantetecnico', '0006_auto_20210326_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compraspublicas',
            name='observacion',
        ),
        migrations.AddField(
            model_name='compraspublicas',
            name='observacion_bodega',
            field=models.TextField(blank=True, null=True, verbose_name='Observación'),
        ),
        migrations.AddField(
            model_name='compraspublicas',
            name='observacion_representante',
            field=models.TextField(blank=True, null=True, verbose_name='Observación'),
        ),
    ]
