# Generated by Django 3.1.5 on 2021-03-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representantetecnico', '0006_auto_20210318_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='compraspublicas',
            name='estado_compra',
            field=models.BooleanField(default=False, null=True, verbose_name='Estado de la compra'),
        ),
    ]
