# Generated by Django 3.1.5 on 2021-03-19 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('representantetecnico', '0007_compraspublicas_estado_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripcion')),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('user_creation', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_representantetecnico_estadocompra', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_representantetecnico_estadocompra', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estado de compra',
                'verbose_name_plural': 'Estado de compras',
                'db_table': 'estado_compra',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='compraspublicas',
            name='estado_compra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='representantetecnico.estadocompra', verbose_name='Estado de compras'),
        ),
    ]
