# Generated by Django 3.1.5 on 2021-04-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representantetecnico', '0007_auto_20210408_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='fecha_entrega',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
