# Generated by Django 3.1.5 on 2021-03-22 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('representantetecnico', '0008_auto_20210319_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compraspublicasdetalle',
            name='cantidad',
        ),
    ]
