# Generated by Django 3.1.5 on 2021-03-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representantetecnico', '0008_auto_20210326_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='codigo_solicitud',
            field=models.CharField(max_length=50, null=True, verbose_name='Codigo de solicitud'),
        ),
    ]
