# Generated by Django 3.1.5 on 2021-04-09 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('representantetecnico', '0008_solicitud_fecha_entrega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='fecha_entrega',
        ),
    ]
