# Generated by Django 3.1.5 on 2021-04-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representantetecnico', '0009_remove_solicitud_fecha_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compraspublicas',
            name='observacion',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Observación'),
        ),
    ]
