# Generated by Django 3.1.5 on 2021-03-28 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('representantetecnico', '0009_solicitud_codigo_solicitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre del mes')),
                ('numero', models.IntegerField(verbose_name='Numero de mes')),
            ],
            options={
                'verbose_name': 'Mes',
                'verbose_name_plural': 'Meses',
                'db_table': 'mes',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='documento',
            name='compra_publica',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='solicitud',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='url_documento',
        ),
        migrations.RemoveField(
            model_name='informesmensuales',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='informesmensuales',
            name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='documento',
            name='documento',
            field=models.FileField(null=True, upload_to='documentos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='documento',
            name='informe_mensual_detalle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='representantetecnico.informesmensualesdetalle'),
        ),
        migrations.AddField(
            model_name='informesmensuales',
            name='is_editable',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo_documento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='representantetecnico.tipodocumento'),
        ),
        migrations.AddField(
            model_name='informesmensuales',
            name='mes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='representantetecnico.mes', verbose_name='Mes'),
        ),
    ]
