# Generated by Django 3.1.5 on 2021-03-23 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('representantetecnico', '0010_compraspublicasdetalle_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='estado_solicitud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='representantetecnico.estadocompra', verbose_name='Estados solicitud'),
        ),
    ]
