# Generated by Django 3.1.5 on 2021-04-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representantetecnico', '0010_auto_20210412_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='informesmensuales',
            name='doc_informe',
            field=models.FileField(null=True, upload_to='informemensual/%Y/%m/%d'),
        ),
    ]
