# Generated by Django 3.1.5 on 2021-04-16 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('representantetecnico', '0011_informesmensuales_doc_informe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repositorio',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='repositorio',
            name='nombre_real',
        ),
        migrations.RemoveField(
            model_name='repositorio',
            name='nombre_usuario',
        ),
        migrations.RemoveField(
            model_name='repositorio',
            name='url',
        ),
        migrations.AddField(
            model_name='repositorio',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='repositorio/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='repositorio',
            name='nombre_carpeta',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nombre carpeta'),
        ),
        migrations.AddField(
            model_name='repositorio',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='representantetecnico.repositorio'),
        ),
    ]
