# Generated by Django 3.1.5 on 2021-03-23 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('representantetecnico', '0011_solicitud_estado_solicitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='is_autorized',
        ),
    ]
