# Generated by Django 3.1.5 on 2021-03-30 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representantetecnico', '0011_auto_20210329_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicituddetalle',
            name='cantidad_consumida',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8, null=True, verbose_name='Cantidad consumida'),
        ),
        migrations.AlterField(
            model_name='solicituddetalle',
            name='cantidad_entregada',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8, null=True, verbose_name='Cantidad entregada'),
        ),
        migrations.AlterField(
            model_name='solicituddetalle',
            name='cantidad_solicitada',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8, null=True, verbose_name='Cantidad solicitada'),
        ),
    ]
