# Generated by Django 3.1.5 on 2021-03-30 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('representantetecnico', '0012_auto_20210329_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desgloseinfomemensualdetalle',
            name='solicitud',
        ),
        migrations.AddField(
            model_name='desgloseinfomemensualdetalle',
            name='solicitud_detalle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='representantetecnico.solicituddetalle'),
        ),
    ]
