# Generated by Django 3.1.5 on 2021-04-16 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('representantetecnico', '0012_auto_20210415_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repositorio',
            old_name='nombre_carpeta',
            new_name='nombre',
        ),
    ]
