# Generated by Django 3.1.5 on 2021-03-30 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('representantetecnico', '0013_auto_20210329_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desgloseinfomemensualdetalle',
            name='documento',
            field=models.FileField(null=True, upload_to='informemensual/sustancias/desglose/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='desgloseinfomemensualdetalle',
            name='solicitud_detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='representantetecnico.solicituddetalle'),
        ),
    ]
