# Generated by Django 3.1.5 on 2021-04-01 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representantetecnico', '0014_auto_20210330_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compraspublicasdetalle',
            name='cantidad',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8, null=True, verbose_name='cantidad'),
        ),
        migrations.AlterField(
            model_name='desgloseinfomemensualdetalle',
            name='cantidad',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8, null=True, verbose_name='cantidad'),
        ),
        migrations.AlterField(
            model_name='informesmensualesdetalle',
            name='cantidad',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8, null=True, verbose_name='cantidad'),
        ),
    ]
