# Generated by Django 3.1.5 on 2021-04-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representantetecnico', '0015_auto_20210331_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='informesmensuales',
            name='year',
            field=models.IntegerField(default=2021, verbose_name='Año'),
        ),
    ]
