# Generated by Django 3.1.5 on 2021-03-18 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratoryworkerprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='laboratoryworkerprofile',
            name='user_creation',
        ),
        migrations.RemoveField(
            model_name='laboratoryworkerprofile',
            name='user_updated',
        ),
        migrations.RemoveField(
            model_name='representativeprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='representativeprofile',
            name='user_creation',
        ),
        migrations.RemoveField(
            model_name='representativeprofile',
            name='user_updated',
        ),
        migrations.DeleteModel(
            name='GrocerProfile',
        ),
        migrations.DeleteModel(
            name='LaboratoryWorkerProfile',
        ),
        migrations.DeleteModel(
            name='RepresentativeProfile',
        ),
    ]
