# Generated by Django 3.1.5 on 2021-01-13 19:59

import CSSF.validators
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True, verbose_name='Nombre de la categoria')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime.now, editable=False)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_documento', models.CharField(max_length=200, unique=True)),
                ('tipo_documento', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'documento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de facultad')),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime.now, editable=False)),
            ],
            options={
                'verbose_name': 'Facultad',
                'verbose_name_plural': 'Facultades',
                'db_table': 'facultad',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='IngresoCompras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=200, verbose_name='Nombre de proyecto')),
                ('convocatoria', models.IntegerField(blank=True, null=True, validators=[CSSF.validators.validate_compras_convocatoria])),
                ('id_facultad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CSSF.facultad')),
            ],
            options={
                'verbose_name': 'IngresoCompra',
                'verbose_name_plural': 'IngresosCompras',
                'db_table': 'ingreso_compra',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombres del solicitante')),
                ('apellido', models.CharField(max_length=25, verbose_name='Apellidos del solicitante')),
                ('cedula', models.CharField(max_length=10, unique=True, verbose_name='Numero de cedula')),
                ('telefono', models.CharField(blank=True, max_length=10, null=True, verbose_name='Numero de telefono')),
                ('correo_electronico', models.CharField(max_length=150, unique=True, verbose_name='Correo electronico')),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime.now, editable=False)),
            ],
            options={
                'verbose_name': 'Solicitante',
                'verbose_name_plural': 'Solicitantes',
                'db_table': 'solicitante',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CSSF.categoria')),
                ('id_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CSSF.solicitante')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'db_table': 'solicitud',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SolicitanteCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sc', models.CharField(max_length=2, null=True, validators=[CSSF.validators.validate_solicitante_compra_tipo_sc])),
                ('id_ingreso_compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CSSF.ingresocompras')),
                ('id_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CSSF.solicitante')),
            ],
            options={
                'verbose_name': 'SolicitanteCompra',
                'verbose_name_plural': 'SolicitantesCompras',
                'db_table': 'solicitante_compra',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de laboratorio')),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('id_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CSSF.solicitante')),
            ],
            options={
                'verbose_name': 'Laboratorio',
                'verbose_name_plural': 'Laboratorios',
                'db_table': 'labratorio',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud_entrega', models.DateTimeField(editable=False, verbose_name=datetime.datetime.now)),
                ('fecha_entrega', models.DateTimeField(editable=False, verbose_name=datetime.datetime.now)),
                ('id_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CSSF.documento')),
                ('id_ingreso_compras', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CSSF.ingresocompras')),
                ('id_laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CSSF.laboratorio')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'db_table': 'entrega',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='id_ingreso_compras',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CSSF.ingresocompras'),
        ),
        migrations.AddField(
            model_name='documento',
            name='id_solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CSSF.solicitud'),
        ),
    ]
