# Generated by Django 3.1.5 on 2021-01-22 01:14

import cssf.validators
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True, verbose_name='Nombre de la categoria')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_documento', models.CharField(max_length=200, unique=True)),
                ('tipo_documento', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'documento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de facultad')),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Facultad',
                'verbose_name_plural': 'Facultades',
                'db_table': 'facultad',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='IngresoCompras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=200, verbose_name='Nombre de proyecto')),
                ('convocatoria', models.IntegerField(blank=True, null=True, validators=[cssf.validators.validate_compras_convocatoria])),
                ('id_facultad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cssf.facultad')),
            ],
            options={
                'verbose_name': 'IngresoCompra',
                'verbose_name_plural': 'IngresosCompras',
                'db_table': 'ingreso_compra',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombres del solicitante')),
                ('apellido', models.CharField(max_length=25, verbose_name='Apellidos del solicitante')),
                ('cedula', models.CharField(max_length=10, unique=True, verbose_name='Numero de cedula')),
                ('telefono', models.CharField(blank=True, max_length=10, null=True, verbose_name='Numero de telefono')),
                ('correo_electronico', models.CharField(max_length=150, unique=True, verbose_name='Correo electronico')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Solicitante',
                'verbose_name_plural': 'Solicitantes',
                'db_table': 'solicitante',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cssf.categoria')),
                ('id_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cssf.solicitante')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'db_table': 'solicitud',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SolicitanteCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sc', models.CharField(max_length=2, null=True, validators=[cssf.validators.validate_solicitante_compra_tipo_sc])),
                ('id_ingreso_compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cssf.ingresocompras')),
                ('id_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cssf.solicitante')),
            ],
            options={
                'verbose_name': 'SolicitanteCompra',
                'verbose_name_plural': 'SolicitantesCompras',
                'db_table': 'solicitante_compra',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de laboratorio')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('id_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cssf.solicitante')),
            ],
            options={
                'verbose_name': 'Laboratorio',
                'verbose_name_plural': 'Laboratorios',
                'db_table': 'labratorio',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud_entrega', models.DateTimeField(editable=False, verbose_name=django.utils.timezone.now)),
                ('fecha_entrega', models.DateTimeField(editable=False, verbose_name=django.utils.timezone.now)),
                ('id_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cssf.documento')),
                ('id_ingreso_compras', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cssf.ingresocompras')),
                ('id_laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cssf.laboratorio')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'db_table': 'entrega',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='id_ingreso_compras',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cssf.ingresocompras'),
        ),
        migrations.AddField(
            model_name='documento',
            name='id_solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cssf.solicitud'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cedula', models.CharField(max_length=10, unique=True, verbose_name='Cedula')),
                ('telefono', models.CharField(max_length=10, verbose_name='Telefono')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
