# Generated by Django 3.1.5 on 2021-02-02 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cssf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositorio',
            name='folder',
            field=models.CharField(default='', max_length=100, verbose_name='Carpeta padre'),
        ),
        migrations.AddField(
            model_name='repositorio',
            name='is_dir',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='repositorio',
            name='is_file',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
