# Generated by Django 3.1.5 on 2021-01-22 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cssf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='auth_user',
        ),
    ]
