# Generated by Django 3.1.5 on 2021-01-13 20:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CSSF', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='fecha_entrega',
            field=models.DateTimeField(editable=False, verbose_name=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='fecha_solicitud_entrega',
            field=models.DateTimeField(editable=False, verbose_name=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='facultad',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_solicitud',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
