# Generated by Django 3.1.5 on 2021-01-29 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cssf', '0002_auto_20210128_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compraspublicas',
            name='id_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_empresa', to='cssf.proveedor', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='compraspublicas',
            name='id_responsable_entrega_compras',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_responsable_entrega_compras', to='cssf.persona', verbose_name='Responsable entrega'),
        ),
        migrations.AlterField(
            model_name='compraspublicas',
            name='id_transportista_compras',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_transportista_compras', to='cssf.persona', verbose_name='Transportista'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='id_responsable_entrega_proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_responsable_entrega_proveedor', to='cssf.persona', verbose_name='Responsable entrega'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='id_transportista_proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_transportista_proveedor', to='cssf.persona', verbose_name='Transportista'),
        ),
    ]
