# Generated by Django 3.1.5 on 2021-01-22 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cssf', '0002_auto_20210121_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorio',
            name='id_solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitantecompra',
            name='id_ingreso_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cssf.ingresocompras'),
        ),
        migrations.AlterField(
            model_name='solicitantecompra',
            name='id_solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='id_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cssf.categoria'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='id_solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Solicitante',
        ),
    ]
