# Generated by Django 3.1.5 on 2021-01-22 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cssf', '0003_auto_20210121_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratorio',
            name='id_solicitante',
        ),
        migrations.CreateModel(
            name='TecnicoLaboratorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('id_laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cssf.laboratorio')),
                ('id_tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TecnicoLaboratorio',
                'verbose_name_plural': 'TecnicosLaboratorios',
                'db_table': 'tecnico_laboratorio',
                'ordering': ['id'],
            },
        ),
    ]
