# Generated by Django 3.1.5 on 2021-01-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cssf', '0003_auto_20210128_2300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['id'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterField(
            model_name='persona',
            name='is_active',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
