# Generated by Django 3.1.5 on 2021-01-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cssf', '0004_auto_20210129_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='nombre',
            field=models.CharField(default='', max_length=100, verbose_name='Nombres'),
        ),
    ]
