# Generated by Django 3.1.5 on 2021-01-26 05:06

import cssf.validators
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cssf', '0004_auto_20210121_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('cedula', models.CharField(max_length=100, unique=True, verbose_name='Cedula')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'persona',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripcion')),
                ('is_active', models.BooleanField(default=True, editable=False)),
            ],
            options={
                'verbose_name': 'TipoDocumento',
                'verbose_name_plural': 'TipoDocumentos',
                'db_table': 'tipo_documento',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='documento',
            name='id_ingreso_compras',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='tipo_documento',
        ),
        migrations.AddField(
            model_name='user',
            name='is_bodeguero',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_laboratorista',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_representante',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documento',
            name='id_solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cssf.solicitud'),
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de empresa')),
                ('ruc', models.CharField(max_length=13, unique=True, verbose_name='Ruc')),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('id_responsable_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_responsable_entrega', to='cssf.persona')),
                ('id_transportista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_transportista', to='cssf.persona')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ComprasPublicas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llegada_bodega', models.DateField(default=datetime.datetime(2021, 1, 26, 5, 6, 27, 159993, tzinfo=utc), verbose_name='Fecha llegada a bodega')),
                ('hora_llegada_bodega', models.TimeField(default=datetime.datetime(2021, 1, 26, 5, 6, 27, 159993, tzinfo=utc), verbose_name='Hora llegada a bodega')),
                ('convocatoria', models.IntegerField(blank=True, null=True, validators=[cssf.validators.validate_compras_convocatoria])),
                ('fecha_registro', models.DateTimeField(default=datetime.datetime(2021, 1, 26, 5, 6, 27, 159993, tzinfo=utc), editable=False)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cssf.proveedor')),
                ('id_responsable_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsable_entrega', to='cssf.persona')),
                ('id_transportista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itransportista', to='cssf.persona')),
            ],
            options={
                'verbose_name': 'CompraPublica',
                'verbose_name_plural': 'ComprasPublicas',
                'db_table': 'compras_publicas',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='id_compra_publica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cssf.compraspublicas'),
        ),
        migrations.AddField(
            model_name='documento',
            name='id_tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cssf.tipodocumento'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='id_ingreso_compras',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cssf.compraspublicas'),
        ),
        migrations.AlterField(
            model_name='solicitantecompra',
            name='id_ingreso_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cssf.compraspublicas'),
        ),
        migrations.DeleteModel(
            name='IngresoCompras',
        ),
    ]
