# Generated by Django 3.1.5 on 2021-01-29 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cssf', '0005_persona_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True, verbose_name='Tipo de persona')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion')),
                ('is_active', models.BooleanField(default=True, editable=False)),
            ],
            options={
                'verbose_name': 'TipoPersona',
                'verbose_name_plural': 'TipoPersonas',
                'db_table': 'tipo_persona',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='id_tipo_persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_tipo_persona', to='cssf.tipopersona'),
        ),
    ]
