# Generated by Django 3.1.5 on 2021-01-26 05:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cssf', '0005_auto_20210126_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compraspublicas',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 26, 5, 8, 39, 570543, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='compraspublicas',
            name='hora_llegada_bodega',
            field=models.TimeField(default=datetime.datetime(2021, 1, 26, 5, 8, 39, 570543, tzinfo=utc), verbose_name='Hora llegada a bodega'),
        ),
        migrations.AlterField(
            model_name='compraspublicas',
            name='id_responsable_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsable_entrega_compra', to='cssf.persona'),
        ),
        migrations.AlterField(
            model_name='compraspublicas',
            name='id_transportista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transportista_compra', to='cssf.persona'),
        ),
        migrations.AlterField(
            model_name='compraspublicas',
            name='llegada_bodega',
            field=models.DateField(default=datetime.datetime(2021, 1, 26, 5, 8, 39, 570543, tzinfo=utc), verbose_name='Fecha llegada a bodega'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='id_responsable_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsable_entrega_proveedor', to='cssf.persona'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='id_transportista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transportista_proveedor', to='cssf.persona'),
        ),
    ]
