# Generated by Django 3.1.5 on 2021-01-29 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cssf', '0006_auto_20210129_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='id_responsable_entrega_proveedor',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='id_transportista_proveedor',
        ),
        migrations.AlterField(
            model_name='persona',
            name='id_tipo_persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_tipo_persona', to='cssf.tipopersona', verbose_name='Tipo de persona'),
        ),
    ]
