# Generated by Django 3.1.5 on 2021-01-26 05:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cssf', '0006_auto_20210126_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compraspublicas',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='compraspublicas',
            name='hora_llegada_bodega',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Hora llegada a bodega'),
        ),
        migrations.AlterField(
            model_name='compraspublicas',
            name='llegada_bodega',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha llegada a bodega'),
        ),
    ]
