# Generated by Django 3.1.5 on 2021-02-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('cantidad_movimiento', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Cantidad movimiento')),
                ('cantidad_movimiento2', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Cantidad movimiento 2')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'inventario',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sustancia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de sustancia')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Cantidad')),
            ],
            options={
                'verbose_name': 'Sustancia',
                'verbose_name_plural': 'Sustancias',
                'db_table': 'sustancia',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoMovimientoInventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('nombre', models.CharField(max_length=20, unique=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Tipo de movimiento de inventario',
                'verbose_name_plural': 'Tipos de movimientos de inventario',
                'db_table': 'tipo_movimiento_inventario',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoPresentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('nombre', models.CharField(max_length=10, verbose_name='Nombre de tipo de presentacion')),
                ('descripcion', models.CharField(blank=True, max_length=10, null=True, verbose_name='Descripción de tipo de presentacion')),
            ],
            options={
                'verbose_name': 'Tipo de presentacion',
                'verbose_name_plural': 'Tipo de presentaciones',
                'db_table': 'tipo_presentacion',
                'ordering': ['id'],
            },
        ),
    ]
