# Generated by Django 3.1.5 on 2021-04-02 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tecnicolaboratorio', '0001_initial'),
        ('bodega', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sustancia',
            name='user_creation',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_bodega_sustancia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sustancia',
            name='user_updated',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_bodega_sustancia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stock',
            name='bodega',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bodega.bodega'),
        ),
        migrations.AddField(
            model_name='stock',
            name='laboratorio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tecnicolaboratorio.laboratorio'),
        ),
        migrations.AddField(
            model_name='stock',
            name='sustancia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bodega.sustancia'),
        ),
        migrations.AddField(
            model_name='stock',
            name='user_creation',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_bodega_stock', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stock',
            name='user_updated',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_bodega_stock', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bodega',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='bodega',
            name='user_creation',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_bodega_bodega', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bodega',
            name='user_updated',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_bodega_bodega', to=settings.AUTH_USER_MODEL),
        ),
    ]
