# Generated by Django 3.1.5 on 2021-02-18 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bodega', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipopresentacion',
            name='user_creation',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_bodega_tipopresentacion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tipopresentacion',
            name='user_updated',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_bodega_tipopresentacion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tipomovimientoinventario',
            name='user_creation',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_bodega_tipomovimientoinventario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tipomovimientoinventario',
            name='user_updated',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_bodega_tipomovimientoinventario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sustancia',
            name='tipo_presentacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.tipopresentacion', verbose_name='TIpo de presentacion'),
        ),
        migrations.AddField(
            model_name='sustancia',
            name='user_creation',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_bodega_sustancia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sustancia',
            name='user_updated',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_bodega_sustancia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventario',
            name='sustancia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.sustancia', verbose_name='Sustancia'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='tipo_movimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bodega.tipomovimientoinventario', verbose_name='Tipo de movimiento de inventario'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='user_creation',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_bodega_inventario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventario',
            name='user_updated',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_bodega_inventario', to=settings.AUTH_USER_MODEL),
        ),
    ]
