# Generated by Django 3.1.5 on 2021-02-18 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0002_auto_20210218_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='cantidad_movimiento2',
        ),
    ]
