# Generated by Django 3.1.5 on 2021-03-25 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0002_auto_20210323_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='cantidad',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=9),
        ),
    ]
