# Generated by Django 3.1.5 on 2021-02-18 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bodega', '0003_remove_inventario_cantidad_movimiento2'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipopresentacion',
            name='volumen',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Volumen'),
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('nombre', models.CharField(max_length=10, verbose_name='Nombre de unidad de medida')),
                ('descripcion', models.CharField(blank=True, max_length=10, null=True, verbose_name='Descripción')),
                ('user_creation', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_bodega_unidadmedida', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_bodega_unidadmedida', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unidad de medida',
                'verbose_name_plural': 'Unidades de medida',
                'db_table': 'unidad_medida',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='tipopresentacion',
            name='unidad_medida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bodega.unidadmedida', verbose_name='Unidad de medida'),
        ),
    ]
