# Generated by Django 3.1.5 on 2021-03-25 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0003_auto_20210324_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipomovimientoinventario',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='tipomovimientoinventario',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='tipomovimientoinventario',
            name='user_creation',
        ),
        migrations.RemoveField(
            model_name='tipomovimientoinventario',
            name='user_updated',
        ),
        migrations.RemoveField(
            model_name='unidadmedida',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='unidadmedida',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='unidadmedida',
            name='user_creation',
        ),
        migrations.RemoveField(
            model_name='unidadmedida',
            name='user_updated',
        ),
    ]
