# Generated by Django 3.1.5 on 2021-02-18 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bodega', '0004_auto_20210218_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='sustancia',
        ),
        migrations.RemoveField(
            model_name='sustancia',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='sustancia',
            name='tipo_presentacion',
        ),
        migrations.AddField(
            model_name='sustancia',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción de la sustancia'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='cantidad_movimiento',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=9, verbose_name='Cantidad movimiento'),
        ),
        migrations.CreateModel(
            name='StockSustancia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('cantidad', models.DecimalField(decimal_places=4, default=0, max_digits=9, verbose_name='Cantidad presentacion')),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.tipopresentacion', verbose_name='Tipo de presentacion')),
                ('sustancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.sustancia', verbose_name='Sustancia')),
                ('user_creation', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_bodega_stocksustancia', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_bodega_stocksustancia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock de sustancia',
                'verbose_name_plural': 'Stock de sustancias',
                'db_table': 'stock_sustancia',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='inventario',
            name='sustancia_stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bodega.stocksustancia', verbose_name='Stock de sustancia'),
        ),
    ]
