# Generated by Django 3.1.5 on 2021-02-24 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0005_auto_20210218_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipopresentacion',
            name='unidad_medida',
        ),
        migrations.RemoveField(
            model_name='tipopresentacion',
            name='user_creation',
        ),
        migrations.RemoveField(
            model_name='tipopresentacion',
            name='user_updated',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='sustancia_stock',
        ),
        migrations.AddField(
            model_name='inventario',
            name='sustancia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bodega.sustancia', verbose_name='Stock de sustancia'),
        ),
        migrations.AddField(
            model_name='sustancia',
            name='cantidad',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=9, verbose_name='Cantidad actual'),
        ),
        migrations.AddField(
            model_name='sustancia',
            name='cupo_autorizado',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=9, verbose_name='Cupo autorizado'),
        ),
        migrations.AddField(
            model_name='sustancia',
            name='unidad_medida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bodega.unidadmedida', verbose_name='Unidad de medida'),
        ),
        migrations.AddField(
            model_name='unidadmedida',
            name='simbolo',
            field=models.CharField(max_length=5, null=True, verbose_name='Simbolo de la unidad de medida'),
        ),
        migrations.AlterField(
            model_name='unidadmedida',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='unidadmedida',
            name='nombre',
            field=models.CharField(max_length=20, verbose_name='Nombre de unidad de medida'),
        ),
        migrations.DeleteModel(
            name='StockSustancia',
        ),
        migrations.DeleteModel(
            name='TipoPresentacion',
        ),
    ]
