# Generated by Django 3.1.5 on 2021-02-25 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bodega', '0006_auto_20210224_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre de unidad de medida')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Direccion')),
                ('user_creation', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_bodega_bodega', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_bodega_bodega', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
                'db_table': 'bodega',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='inventario',
            name='bodega',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bodega.bodega', verbose_name='Bodega'),
        ),
    ]
