# Generated by Django 3.1.5 on 2021-02-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0008_bodega_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='nombre',
            field=models.CharField(max_length=20, verbose_name='Nombre'),
        ),
    ]
