# Generated by Django 3.1.5 on 2021-02-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0010_auto_20210226_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sustancia',
            name='cantidad',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=9, verbose_name='Saldo inicial'),
        ),
    ]
