# Generated by Django 3.1.5 on 2021-02-27 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0012_auto_20210226_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sustancia',
            name='cantidad',
        ),
    ]
