# Generated by Django 3.1.5 on 2021-03-19 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0013_remove_sustancia_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='sustancia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bodega.sustancia'),
        ),
    ]
