# Generated by Django 3.1.5 on 2021-04-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicolaboratorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorio',
            name='direccion',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Dirección'),
        ),
    ]
