# Generated by Django 3.1.5 on 2021-02-14 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tecnicolaboratorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorio',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='user_creation',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_tecnicolaboratorio_laboratorio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='user_updated',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_tecnicolaboratorio_laboratorio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tecnicolaboratorio',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tecnicolaboratorio',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='tecnicolaboratorio',
            name='user_creation',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_tecnicolaboratorio_tecnicolaboratorio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tecnicolaboratorio',
            name='user_updated',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_tecnicolaboratorio_tecnicolaboratorio', to=settings.AUTH_USER_MODEL),
        ),
    ]
